name: Schedule Smoke Test
on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes (UTC) for testing
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "UTC now: $(date -u)"
          echo "MYT now: $(TZ=Asia/Kuala_Lumpur date)"
